#!/usr/bin/env python
import argparse
import os
import logging.config
import json
import ocdskingfisherviews.cli.util
import ocdskingfisherprocess.config


def main():

    config = ocdskingfisherprocess.config.Config()
    config.load_user_config()

    #logging_config_file_full_path = os.path.expanduser('~/.config/ocdskingfisher-process/logging.json')
    #if os.path.isfile(logging_config_file_full_path):
        #with open(logging_config_file_full_path) as f:
            #logging.config.dictConfig(json.load(f))

    parser = argparse.ArgumentParser()
    #parser.add_argument("--quiet", help="remove output",
                        #action="store_true")

    subparsers = parser.add_subparsers(dest='subcommand')

    commands = ocdskingfisherviews.cli.util.gather_cli_commands_instances(config=config)

    for command in commands.values():
        command.configure_subparser(subparsers.add_parser(command.command))

    args = parser.parse_args()

    if args.subcommand and args.subcommand in commands.keys():
        commands[args.subcommand].run_command(args)
    else:
        print("Please select a subcommand (try --help)")


if __name__ == '__main__':
    main()
