[project]
name = "kingfisher-summarize"
version = "0.0.0"

[tool.ruff]
line-length = 119
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN", "COM", "EM",
  # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  "W191", "D206", "Q000", "Q001", "Q002", "Q003", "ISC001",
  "D203", "D212",  # ignore incompatible rules
  "D200",  # documentation preferences
  "C901", "PLR091",  # complexity preferences
  "PTH",  # pathlib
  "ARG001",  # click callbacks
  "D100", "D101", "D104", # docstrings
  "D301",  # click escapes
  "INP001",  # migrations directory
  "PLW0603",  # global db
  "PLW2901",  # row overwritten
  "S324",  # md5 hash
  "TRY003",  # click exceptions
]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["copyright"]

[tool.ruff.lint.per-file-ignores]
"docs/conf.py" = ["INP001"]  # no __init__.py file
"migrations/*" = ["D", "T201"]  # print
"tests/*" = [
  "D",  # docstring
  "ARG001",  # Unused function argument
  "DTZ001",  # tzinfo
  "PLR2004",  # Magic value used
  "S101",  # assert
]

[tool.coverage.run]
concurrency = ["multiprocessing"]
parallel = true
sigterm = true

[tool.pytest.ini_options]
log_level = "INFO"
